# Generated by Django 5.2.4 on 2025-08-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestId', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('status', models.TextField()),
                ('amount', models.FloatField()),
                ('paymentMethod', models.CharField()),
            ],
        ),
    ]
