# Generated by Django 5.2.4 on 2025-08-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='requestId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
