# Generated by Django 5.2.4 on 2025-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='summa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
