# Generated by Django 5.2.4 on 2025-07-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
