# Generated by Django 5.2.4 on 2025-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_deliver_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver',
            field=models.CharField(default='Без курьера', max_length=255),
        ),
    ]
