# Generated by Django 5.2.4 on 2025-08-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_payment',
            field=models.CharField(default='Наличные', max_length=255),
        ),
    ]
